### ISSUE TITLE
Please push NTLM changes to NPM

### ISSUE THREAD

**Issue by jdarling** [jclulow/node-smbhash#1]
Can you uprev your version number and push the NTLM (with a working example would be great) so regular npm install will work?  Currently if you do an npm install smbhash you don't get NTLM support with it.

**Comment by jclulow** [comment]
So, you can refer directly to a git repository URL in your `package.json` file, rather than pulling it from NPM.

I haven't released a version of the module with the NTLM Authentication stuff because I'm not 100% convinced that it actually works.  When I was working on it initially I had access to something that I could test it with, but that's unfortunately not the case at this point.

If you have an IIS server on the Internet to test it against, it should hopefully be relatively easy to verify.  If I can see that it works I'm happy to release a new version.

**Comment by tomasdev** [comment]
As per #2, not currently working.
